### ISSUE TITLE
Option to display full URLs

### ISSUE THREAD

**Issue by chneukirchen** [jarun/ddgr#19]
It would be nice to print the full URLs for the found pages, so one can use `--np` and still click on them on a suitable terminal emulator.

**Comment by jarun** [comment]
Please use option `-x` to display the URLs in full.

**Comment by jarun** [comment]
Since we have a related defect, here's my rationale behind showing only domain names by default:
- unlike `googler`, there's no way to control the number of results with `ddgr` and the results are too many (30, 50) per page for most queries. To accommodate them in lesser lines, I have squeezed in the domain name along with the title. Users who want the complete url can always use the `-x` option and alias it (`alias ddgr="ddgr -x"`)
- `ddgr` is for the terminal, one is not supposed to touch the mouse ;). The omniprompt `o` or `O` keys should be used to open a result.

**Comment by chneukirchen** [comment]
Wow, I totally missed `-x`!. Thank you!

**Comment by jarun** [comment]
No problem!
