### ISSUE TITLE
[ERROR] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by kroosie** [jarun/ddgr#76]
```
$ ddgr -x 'h\"/:=\"'
[ERROR] HTTP Error 403: Forbidden
No results.
$ ddgr -v 
1.5
``` 
Searching 'h\"/:=\"' in duckduckgo.com gives the following result: 
https://duckduckgo.com/?q=%27h%5C"%2F%3A%3D%5C"%27&t=h_&ia=web
I didn't expect any meaningful results but I didn't expect a 403 either.

**Comment by jarun** [comment]
I am not sure what made you think a particular string would lead to forbidden network. For me:

```
$ ddgr -x 'h\"/:=\"'
No results.
ddgr (? for help)
```

The result is same when you search the string at https://duckduckgo.com/html.

The network error is probably because of any anomaly the DDG server detected with your IP. Sometimes similar error shows when trying to search over Tor or a proxy.

**Comment by IGotADreamInMind** [comment]
Sorry just got the email. Hadn't realized I even subscribed.

**Comment by kroosie** [comment]
@jarun when i search the string on duckduckgo i get results about h&m and random stuff, although when i search the string on ddgr i get no results.
