### ISSUE TITLE
Termux - Can't Opened in the Browser

### ISSUE THREAD

**Issue by mskian** [jarun/ddgr#77]
Hi, 

I am using `ddgr` in Termux Install via Python3 pip

While try to Open the search result in Browser I got this below error

```
[Error] Could not locate runnable browser
````

**Comment by jarun** [comment]
Install w3m if not installed already. Then:

    export BROWSER=w3m

**Comment by kxxvii** [comment]
@mskian @jarun Another way to go about it is to set it to `termux-open-url`, so something like `export BROWSER=termux-open-url`.

If you're using termux I guess you wanna do stuff in a terminal emulator, but if you'd want to open it in something like Firefox that's one way it could be done. (Well, likely would do it).
 
Was a while since I read the `ddgr` docs (and code), but I guess that might be a reasonable default setting since that's provided _without_ any terminal-api add-on, if I'm not mistaken. I don't think any terminal browser comes with termux by default. At least not as far as I can tell when installed from [F-Droid](https://f-droid.org/).
