### ISSUE TITLE
ddgr returns 0 exit code on HTTP Errors

### ISSUE THREAD

**Issue by drmcnelson** [jarun/ddgr#83]
When using dggr with -w scholar.google.com ,  google may after a while, block the request.  In this scenario, "[ERROR] HTTP Error 403: Forbidden" is sent to stderr, then ddgr exits, and the exit code is 0.

Internally, the fetch routines raise a DGConnectionError,  calls LOGERR(e), and returns None, after which dggr exits with no error code.

This makes it difficulty to use ddgr from another script, for example to loop over a set of searches and wait and repeat the last search, when google blocks.

As a temporary measure,  I inserted a line  sys.exit(1)  after the call to LOGERR(e), perhaps depending on the content of the error.

**Comment by jarun** [comment]
Please raise a PR with your changes.

**Comment by drmcnelson** [comment]
I have not looked at the code in more than a quick perusal.   Are you 
saying that the patch  I made is consistent with the way the code is 
supposed to work and does not break some other important use case?

**Comment by jarun** [comment]
please share the patch.

**Comment by jarun** [comment]
I asked for it because I wanted to get the relevant line number. Anyway, as you are looking for the exit code, I think you are scripting some kind of automation so you have already figured out how to get past it. Closing the issue.

**Comment by drmcnelson** [comment]
Incorrect, it is in fact a bug.   You are returning success on an error condition.  See lines 752 and 773 in the attached for my work around.   

[ddgr.zip](https://github.com/jarun/ddgr/files/3001404/ddgr.zip)

**Comment by jarun** [comment]
@drmcnelson your changes are on a older version of `ddgr`. So I am finding it difficult to figure out the exact changes from the many diffs with latest version. But, here are some notes:

- `ddgr` is primarily supposed to work in a REPL mode. So it shouldn't exit (and hence return an error code) if there is a network fetch error. You are probably using it in a oneshot mode and I am not inclined to add checks everywhere that it's a oneshot mode and handle it.
- `https_get()` throws an Exception and that is logged duly in `fetch_instant_answer()`. Again, as REPL is the intended mode it is not propagated down.
- The same applies to `fetch()`. The error is suppressed at one level because the intended mode it not oneshot and the program doesn't error out.

If your intention is to always use `ddgr` in oneshot mode I think the checks you have added are fine and please use the patched version. `ddgr` is kind of in a feature freeze and there won't be too many releases going forward other than significant functional issues.
